# Generated by Django 4.0.4 on 2022-04-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('descrição', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('duração', models.CharField(max_length=50)),
                ('dataCadastro', models.CharField(max_length=10)),
                ('função', models.CharField(max_length=100)),
            ],
        ),
    ]
